# Market Parameters Configuration File
# This file contains all adjustable parameters for the trading engine
# Format: TOML (Tom's Obvious Minimal Language)

#######################################
### GENERAL TRADING PARAMETERS ###
#######################################
[general]
# Maximum position size as percentage of total capital (Risk Management)
# Example: 0.02 = 2% of portfolio per instrument
max_position_size = 0.02

# Default leverage for margin trading (1 = spot trading)
# Warning: Higher leverage increases risk!
default_leverage = 3

#######################################
### MARKET MAKING STRATEGY PARAMETERS ##
#######################################
[market_making]
# Spread multiplier for volatility-adjusted pricing
# Formula: spread = volatility * multiplier
# Higher values = wider spreads, less fills but more profit per trade
spread_multiplier = 1.5

# Inventory threshold for auto-rebalancing (0-1)
# When inventory exceeds this percentage of max_position_size, rebalance triggers
inventory_skew_threshold = 0.3

# Volatility calculation window in minutes
# Longer windows = smoother but slower-responding volatility measures
volatility_window = 30

# Base order size in quote currency (e.g., USDT)
order_size = 100.0

#######################################
### RISK MANAGEMENT PARAMETERS ###
#######################################
[risk]
# Maximum allowed daily loss before shutdown (-0.05 = -5%)
max_daily_loss = -0.05

# Circuit breaker volatility thresholds (standard deviations)
# Triggers progressively stricter actions when breached:
# Level 1: 0.1 (10%) - Reduce position sizes
# Level 2: 0.2 (20%) - Cancel all pending orders
# Level 3: 0.3 (30%) - Full shutdown and liquidation
circuit_breaker_thresholds = [0.1, 0.2, 0.3]

# Maximum allowed slippage percentage for market orders
max_slippage = 0.005  # 0.5%

#######################################
### EXCHANGE-SPECIFIC PARAMETERS ###
#######################################
[exchange.binance]
# Minimum order sizes for Binance
btc_usdt_min_qty = 0.0001  # Minimum BTC quantity
btc_usdt_min_notional = 10.0  # Minimum order value in USDT

[exchange.ftx]
# FTX-specific parameters
btc_usdt_min_qty = 0.0001
btc_usdt_min_notional = 1.0

#######################################
### DATA FEED CONFIGURATION ###
#######################################
[data]
# Primary data source (options: 'ccxt', 'polygon', 'custom')
data_source = "ccxt"

# Time between data updates in seconds
update_interval = 5

# List of instruments to monitor
watchlist = [
    "BTC/USDT",
    "ETH/USDT",
    "SOL/USDT"
]

#######################################
### PERFORMANCE METRICS SETTINGS ###
#######################################
[metrics]
# Sharpe ratio calculation window (in days)
sharpe_window = 30

# Whether to track and report t-statistics
enable_t_stats = true

# Maximum expected drawdown threshold
drawdown_alert_threshold = -0.15  # -15%